version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: datagaze_postgres
    environment:
      POSTGRES_DB: datagaze_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
